name: OCD Cleaners
favicon: null
layout_spectrum: 0.28804473322816193
typography_spectrum: 0.4971738059539348
title: OCD Cleaners of Seattle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77807523-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9076713402755558
  lightness: 0.41005259472876787
  saturation: 0.44108662544749677
  rhythmicContrast: 0.8900700095109642
purpose: []
