name: OCD Cleaners
favicon: null
layout_spectrum: 0.28804473322816193
typography_spectrum: 0.4971738059539348
title: OCD Cleaners of Seattle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77807523-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d3c28'
    - '#85c463'
    - '#ffffff'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
